export const APP_RESOURCE_LOADING = 'APP_RESOURCE_LOADING';
export const APP_RESOURCE_LOADING_COMPLETE = 'APP_RESOURCE_LOADING_COMPLETE';

export const ADD_USER = 'ADD_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
